version: "3"

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: mperformance
      MYSQL_USER: weifan
      MYSQL_PASSWORD: mpower
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql # Data on external volume (persist when container is stopped!)
    container_name: 140lab3db # so we can connect easily

  rest:
    build:
      context: ./rest
    env_file:
      credentials.env
    ports:
      - 5001:5000
    volumes:
      - ./rest/src:/app

  ui:
    build:
      context: ./ui
    environment:
      - REST_SERVER=http://rest:5000
    ports:
      - 5000:5000
    volumes:
      - ./ui/src:/app
